name = "Recorder"
uuid = "c5f2e5b5-9010-42ac-aa93-6ef73b86c405"
authors = ["Michele Mesiti <michele.mesiti@kit.edu>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
